<div class="admin">
    <table>
        <tr>
            <td>
                Username
            </td>
            <td>
                Password
            </td>
            <td>
                Role
            </td>
        </tr>
    {content}
    <tr>
        <td>
            {name}
        </td>
        <td>
            {password}
        </td>
        <td>
            {role}
        </td>
    </tr>
    {/content}
    </table>
</div>